export default function TermsPage() {
  return (
    <div className="container" style={{ paddingTop: "4rem", paddingBottom: "4rem", maxWidth: "800px" }}>
      <h1 className="gradient-text" style={{ fontSize: "2.5rem", marginBottom: "2rem" }}>Terms of Service</h1>
      <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem", color: "var(--fg-muted)", lineHeight: 1.7 }}>
        <p><strong>Last Updated: June 20, 2026</strong></p>
        
        <h3 style={{ color: "var(--fg-default)", marginTop: "1rem" }}>1. Acceptance of Terms</h3>
        <p>By accessing and using 2GOSOO AI Prompt Lab ("the Site"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use our website.</p>

        <h3 style={{ color: "var(--fg-default)", marginTop: "1rem" }}>2. Use of License</h3>
        <p>
          The prompts and content provided on this Site are for informational and educational purposes. You are free to copy and use the AI prompts for your personal or commercial projects. However, you may not mass-scrape, republish, or sell our proprietary prompt templates and analytical articles as your own intellectual property.
        </p>

        <h3 style={{ color: "var(--fg-default)", marginTop: "1rem" }}>3. Disclaimer</h3>
        <p>
          The materials on the Site are provided on an 'as is' basis. 2GOSOO AI Prompt Lab makes no warranties, expressed or implied, and hereby disclaims all other warranties including, without limitation, implied warranties of merchantability or fitness for a particular purpose. We do not guarantee the specific output generated by third-party AI models (e.g., ChatGPT, Claude) using our prompts.
        </p>

        <h3 style={{ color: "var(--fg-default)", marginTop: "1rem" }}>4. Limitations</h3>
        <p>
          In no event shall 2GOSOO AI Prompt Lab or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on the Site.
        </p>

        <h3 style={{ color: "var(--fg-default)", marginTop: "1rem" }}>5. Revisions and Errata</h3>
        <p>
          The materials appearing on the Site could include technical, typographical, or photographic errors. We do not warrant that any of the materials on its website are accurate, complete, or current. We may make changes to the materials contained on its website at any time without notice.
        </p>
      </div>
    </div>
  );
}
